lb-sync-web: add option to sync search index from staging
When we make search changes that require a search index rebuild, we do the rebuild on staging and then we want to replace the search indexes on the live servers.

diff --git a/bin/lb-sync-web b/bin/lb-sync-web
--- a/bin/lb-sync-web
+++ b/bin/lb-sync-web
@@ -1,7 +1,23 @@
 #!/bin/bash
 # 
 # Syncs the Letterboxd staging web root to application servers
-# usage: sync-server.sh <server>+
+# usage: sync-server.sh [-s] <server>+
+
+SYNC_SEARCH_INDEX=0
+
+while getopts ":s" opt; do
+  case $opt in
+    s)
+      SYNC_SEARCH_INDEX=1
+      echo "Will sync staging server search index"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
+
+shift $((OPTIND-1))
 
 $(dirname $0)/lb-ssh-add
 if [ $? != 0 ]; then
@@ -24,6 +40,11 @@ ssh $SERVER '/opt/letterboxd/sbin/lb-archive-web'
 
 echo "$SERVER: Syncing web root..."
 rsync -av --stats --delete /srv/www/staging/web $SERVER:/srv/www/letterboxd
+
+if [ $SYNC_SEARCH_INDEX == 1 ]; then
+	echo "$SERVER: Syncing search index from staging..."
+	rsync -av --delete /srv/tomcat/staging/temp/sm_search_letterboxd/ $SERVER:/srv/tomcat/letterboxd/temp/sm_search_letterboxd/
+fi
 
 echo "$SERVER: Starting application server..."
 ssh $SERVER 'su - letterboxd -c "rm -rf work"'
